### ISSUE TITLE
Restarting a user crashes the frontend

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/almond-cloud#196]
> Feb 01 16:13:01 thingpedia1 node[14342]: Child with ID XXX exited with code 1
> Feb 01 16:13:01 thingpedia1 thingengine-child-XXX[14450]: Stopping engine of XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> Feb 01 16:13:01 thingpedia1 thingengine-child-XXX[14450]: Engine stopped
> Feb 01 16:13:01 thingpedia1 node[14344]: Socket to user ID XXX closed
> Feb 01 16:13:01 thingpedia1 thingengine-child-XXX[14450]: Engine closed
> Feb 01 16:13:01 thingpedia1 node[14344]: POST /me/status/kill 303 9.134 ms - 68
> Feb 01 16:13:01 thingpedia1 node[14344]: /opt/thingengine/node_modules/transparent-rpc/node_modules/q/q.js:155
> Feb 01 16:13:01 thingpedia1 node[14344]: throw e;
> Feb 01 16:13:01 thingpedia1 node[14344]: ^
> Feb 01 16:13:01 thingpedia1 node[14344]: Error: Socket closed
> Feb 01 16:13:01 thingpedia1 node[14344]: at RpcSocket.call (/opt/thingengine/node_modules/transparent-rpc/rpc_socket.js:168:29)
> Feb 01 16:13:01 thingpedia1 node[14344]: at RpcProxy.(anonymous function) [as closeConversation] (/opt/thingengine/node_modules/transparent-rpc/rpc_socket.js:356:37)
> Feb 01 16:13:01 thingpedia1 node[14344]: at WebSocket.ws.on (/opt/thingengine/routes/my_api.js:283:44)
> Feb 01 16:13:01 thingpedia1 node[14344]: at emitTwo (events.js:131:20)
> Feb 01 16:13:01 thingpedia1 node[14344]: at WebSocket.emit (events.js:214:7)
> Feb 01 16:13:01 thingpedia1 node[14344]: at WebSocket.emitClose (/opt/thingengine/node_modules/ws/lib/websocket.js:172:10)
> Feb 01 16:13:01 thingpedia1 node[14344]: at Socket.socketOnClose (/opt/thingengine/node_modules/ws/lib/websocket.js:781:15)
> Feb 01 16:13:01 thingpedia1 node[14344]: at emitOne (events.js:116:13)
> Feb 01 16:13:01 thingpedia1 node[14344]: at Socket.emit (events.js:211:7)
> Feb 01 16:13:01 thingpedia1 node[14344]: at TCP._handle.close [as _onclose] (net.js:561:12)
> Feb 01 16:13:01 thingpedia1 node[14343]: Socket to user ID XXX closed
> Feb 01 16:13:01 thingpedia1 node[14343]: Failed to retrieve cached modules: Invalid user ID
> Feb 01 16:13:01 thingpedia1 node[14343]: Socket to user ID XXX closed

**Comment by gcampax** [comment]
The call to closeConversation is now protected, and I have not seen this crash recently. Closing.
