### ISSUE TITLE
prepare-training fails in staging

### ISSUE THREAD

**Issue by jgd5** [stanford-oval/almond-cloud#517]
Not sure if this is a known issue.  Prepare-training is failing in staging with following error:

```                                           
Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (/opt/almond-cloud/node_modules/mysql/lib/protocol/Protocol.js:212:16)
    at Protocol._enqueue (/opt/almond-cloud/node_modules/mysql/lib/protocol/Protocol.js:138:13)
    at PoolConnection.query (/opt/almond-cloud/node_modules/mysql/lib/Connection.js:201:25)
    at process._tickCallback (internal/process/next_tick.js:61:11)
From previous event:
    at Object.selectAll (/opt/almond-cloud/util/db.js:98:40)
    at Object.getValues (/opt/almond-cloud/model/strings.js:58:19)
    at DatabaseParameterProvider._getStrings (/opt/almond-cloud/training/lib/param_provider.js:22:28)
    at DatabaseParameterProvider.get (/opt/almond-cloud/training/lib/param_provider.js:38:25)
    at ValueListLoader._load (/opt/almond-cloud/node_modules/genie-toolkit/lib/replace_parameters.js:126:43)
    at ValueListLoader.get (/opt/almond-cloud/node_modules/genie-toolkit/lib/replace_parameters.js:120:30)
    at ParameterReplacer._sampleParam (/opt/almond-cloud/node_modules/genie-toolkit/lib/replace_parameters.js:270:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at DatasetAugmenter.onerror (_stream_readable.js:733:7)
    at DatasetAugmenter.emit (events.js:198:13)
    at DatasetAugmenter.EventEmitter.emit (domain.js:448:20)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at DatasetAugmenter.afterTransform (_stream_transform.js:94:3)
    at _process.then (/opt/almond-cloud/node_modules/genie-toolkit/lib/dataset_augmenter.js:90:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by gcampax** [comment]
It is known, and I also have a half-finished fix. I will open a PR when I finish testing it.
