### ISSUE TITLE
prepare-training-set on staging fails with error  `missing entity MEASURE_byte_0`

### ISSUE THREAD

**Issue by jgd5** [stanford-oval/almond-cloud#521]
I'm seeing this new error on staging:

```
/opt/almond-cloud/training/synthetic-gen-process.js:16
process.on('unhandledRejection', (up) => { throw up; });
                                           ^

Error: missing entity MEASURE_byte_0
    at makeDummyEntity (/opt/almond-cloud/node_modules/genie-toolkit/lib/utils.js:199:15)
    at makeDummyEntities (/opt/almond-cloud/node_modules/genie-toolkit/lib/utils.js:215:35)
    at Promise.all.minibatch.map (/opt/almond-cloud/node_modules/genie-toolkit/lib/sentence-generator/index.js:449:30)
    at Array.map (<anonymous>)
    at ContextualSentenceGenerator._process (/opt/almond-cloud/node_modules/genie-toolkit/lib/sentence-generator/index.js:446:54)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at ContextualSentenceGenerator.onerror (_stream_readable.js:733:7)
    at ContextualSentenceGenerator.emit (events.js:198:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at ContextualSentenceGenerator.afterTransform (_stream_transform.js:94:3)
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:788:14)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at Socket._destroy (net.js:613:3)
    at Socket.destroy (internal/streams/destroy.js:37:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:790:10)
```

**Comment by gcampax** [comment]
Yeah that's for contextual models, those need some additional amount of work...
