### ISSUE TITLE
Error sending verification email

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/almond-cloud#601]
Spotted from the logs:
```
Nov 13 11:03:50 thingpedia1 main.js[17943]: { Error: No recipients defined
Nov 13 11:03:50 thingpedia1 main.js[17943]: at SMTPConnection._formatError (/opt/thingengine/node_modules/nodemailer/lib/smtp-connection/index.js:771:19)
Nov 13 11:03:50 thingpedia1 main.js[17943]: at SMTPConnection._setEnvelope (/opt/thingengine/node_modules/nodemailer/lib/smtp-connection/index.js:982:34)
Nov 13 11:03:50 thingpedia1 main.js[17943]: at SMTPConnection.send (/opt/thingengine/node_modules/nodemailer/lib/smtp-connection/index.js:609:14)
Nov 13 11:03:50 thingpedia1 main.js[17943]: at sendMessage (/opt/thingengine/node_modules/nodemailer/lib/smtp-transport/index.js:227:28)
Nov 13 11:03:50 thingpedia1 main.js[17943]: at connection.login.err (/opt/thingengine/node_modules/nodemailer/lib/smtp-transport/index.js:285:25)
Nov 13 11:03:50 thingpedia1 main.js[17943]: at SMTPConnection._actionAUTHComplete (/opt/thingengine/node_modules/nodemailer/lib/smtp-connection/index.js:1519:9)
Nov 13 11:03:50 thingpedia1 main.js[17943]: at SMTPConnection._responseActions.push.str (/opt/thingengine/node_modules/nodemailer/lib/smtp-connection/index.js:544:26)
Nov 13 11:03:50 thingpedia1 main.js[17943]: at SMTPConnection._processResponse (/opt/thingengine/node_modules/nodemailer/lib/smtp-connection/index.js:929:20)
Nov 13 11:03:50 thingpedia1 main.js[17943]: at SMTPConnection._onData (/opt/thingengine/node_modules/nodemailer/lib/smtp-connection/index.js:736:14)
Nov 13 11:03:50 thingpedia1 main.js[17943]: at TLSSocket.SMTPConnection._onSocketData.chunk (/opt/thingengine/node_modules/nodemailer/lib/smtp-connection/index.js:189:44)
Nov 13 11:03:50 thingpedia1 main.js[17943]: From previous event:
Nov 13 11:03:50 thingpedia1 main.js[17943]: at Object.send (/opt/thingengine/util/sendmail.js:39:18)
Nov 13 11:03:50 thingpedia1 main.js[17943]: at sendValidationEmail (/opt/thingengine/routes/user.js:259:21)
Nov 13 11:03:50 thingpedia1 main.js[17943]: at <anonymous>
Nov 13 11:03:50 thingpedia1 main.js[17943]: at process._tickDomainCallback (internal/process/next_tick.js:229:7) code: 'EENVELOPE', command: 'API' }
Nov 13 11:03:50 thingpedia1 main.js[17943]: POST /user/resend-verification 500 434.418 ms - 4785
```

**Comment by gcampax** [comment]
I suspect this happens for Login with Github, as sometimes it doesn't send us an email back. In that case, we should not say that a verification email has been sent in views/register_success.pug, and instead invite the user to enter their email in /user/profile.
