### ISSUE TITLE
Crash during single-engine restart in almond-dev

### ISSUE THREAD

**Issue by gcampax** [stanford-oval/almond-cloud#784]
While a conversation is open in another tab:
```
Jul 27 09:06:25 crowdie thingengine-child-1[21736]: Uncaught error in dialog loop TypeError: $import(...) is not a function
Jul 27 09:06:25 crowdie thingengine-child-1[21736]:     at eval (eval at parse (/opt/thingengine/node_modules/genie-toolkit/lib/sentence-generator/compiler/index.js:130:25), <anonymous>:33:108)
Jul 27 09:06:25 crowdie thingengine-child-1[21736]:     at SentenceGenerator.initialize (/opt/thingengine/node_modules/genie-toolkit/lib/sentence-generator/generator.js:121:19)
Jul 27 09:06:25 crowdie thingengine-child-1[21736]: (node:2) UnhandledPromiseRejectionWarning: TypeError: $import(...) is not a function
Jul 27 09:06:25 crowdie thingengine-child-1[21736]:     at eval (eval at parse (/opt/thingengine/node_modules/genie-toolkit/lib/sentence-generator/compiler/index.js:130:25), <anonymous>:33:108)
Jul 27 09:06:25 crowdie thingengine-child-1[21736]:     at SentenceGenerator.initialize (/opt/thingengine/node_modules/genie-toolkit/lib/sentence-generator/generator.js:121:19)
Jul 27 09:06:25 crowdie thingengine-child-1[21736]: (node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
Jul 27 09:06:25 crowdie thingengine-child-1[21736]: (node:2) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by gcampax** [comment]
I don't think this applies any more because the Genie compiler was refactored quite a bit and the race that triggered this no longer applies.
